import { act, cleanup, renderHook } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { useTeamPositions } from './useTeamPositions'
const snapshot = (time: number, x = 100) => ({ as_of: new Date(time).toISOString(), online_count: 1, positioned: 1, players: [{ user_id: 'u', name: 'U', x, y: -100 }] })
afterEach(() => { cleanup(); vi.useRealTimers() })
it('polls serially, keeps last-known data on failures and stops when hidden', async () => {
  vi.useFakeTimers(); vi.setSystemTime(100000)
  const fetch = vi.fn().mockResolvedValue(snapshot(100000))
  const { result, rerender, unmount } = renderHook(({ active }) => useTeamPositions(fetch, 'https://box.test', active), { initialProps: { active: true } })
  await act(async () => {})
  expect(result.current.data?.players[0].x).toBe(100)
  fetch.mockRejectedValue(new Error('offline'))
  await act(async () => { await vi.advanceTimersByTimeAsync(5000) })
  expect(result.current.error).toBeTruthy()
  expect(result.current.data?.players[0].x).toBe(100)
  rerender({ active: false })
  await act(async () => { await vi.advanceTimersByTimeAsync(60000) })
  expect(fetch).toHaveBeenCalledTimes(2)
  unmount()
  expect(vi.getTimerCount()).toBe(0)
})
it('rejects older snapshots and expires unchanged snapshots', async () => {
  vi.useFakeTimers(); vi.setSystemTime(100000)
  const fetch = vi.fn().mockResolvedValue(snapshot(100000))
  const { result } = renderHook(() => useTeamPositions(fetch, 'https://box.test', true))
  await act(async () => {})
  fetch.mockResolvedValue(snapshot(90000, 200))
  await act(async () => { await vi.advanceTimersByTimeAsync(20000) })
  expect(result.current.data?.players[0].x).toBe(100)
  expect(result.current.stale).toBe(true)
})
it('does not overlap slow requests and aborts on unmount', async () => {
  vi.useFakeTimers()
  const fetch = vi.fn((_url: string, _signal: AbortSignal) => new Promise(() => {}))
  const { unmount } = renderHook(() => useTeamPositions(fetch, 'https://box.test', true))
  await act(async () => { await vi.advanceTimersByTimeAsync(60000) })
  expect(fetch).toHaveBeenCalledTimes(1)
  expect(fetch.mock.calls[0][1].aborted).toBe(true)
  unmount()
  expect(vi.getTimerCount()).toBe(0)
})
it('retains last-known data and ordering across visibility resume', async () => {
  vi.useFakeTimers(); vi.setSystemTime(100000)
  const fetch = vi.fn().mockResolvedValue(snapshot(100000))
  const { result, rerender } = renderHook(({ active }) => useTeamPositions(fetch, 'https://box.test', active), { initialProps: { active: true } })
  await act(async () => {})
  rerender({ active: false })
  fetch.mockResolvedValue(snapshot(90000, 200))
  rerender({ active: true })
  await act(async () => {})
  expect(result.current.data?.players[0].x).toBe(100)
  rerender({ active: false })
  fetch.mockRejectedValue(new Error('offline'))
  rerender({ active: true })
  await act(async () => {})
  expect(result.current.data?.players[0].x).toBe(100)
})
it('preserves the player array when only the observation timestamp changes', async () => {
  vi.useFakeTimers(); vi.setSystemTime(100000)
  const fetch = vi.fn().mockResolvedValue(snapshot(100000))
  const { result } = renderHook(() => useTeamPositions(fetch, 'https://box.test', true))
  await act(async () => {})
  const players = result.current.data?.players
  fetch.mockResolvedValue(snapshot(105000))
  await act(async () => { await vi.advanceTimersByTimeAsync(5000) })
  expect(result.current.data?.players).toBe(players)
})
const atTravel = (time: number, end = false) => ({ ...snapshot(time), players: [{ user_id: 'u', name: 'U', x: end ? -265220 : -108666.8, y: end ? 173530 : 79119.9 }] })
it('records one teleport per observation pair and expires it without new samples', async () => {
  vi.useFakeTimers(); vi.setSystemTime(100000)
  const fetch = vi.fn().mockResolvedValue(atTravel(100000))
  const { result } = renderHook(() => useTeamPositions(fetch, 'https://box.test', true))
  await act(async () => {})
  fetch.mockResolvedValue(atTravel(105000, true))
  await act(async () => { await vi.advanceTimersByTimeAsync(5000) })
  expect(result.current.teleports).toHaveLength(1)
  await act(async () => { await vi.advanceTimersByTimeAsync(5000) })
  expect(result.current.teleports).toHaveLength(1)
  await act(async () => { await vi.advanceTimersByTimeAsync(30000) })
  expect(result.current.teleports).toHaveLength(0)
})
it('does not infer teleports across a failed request or hidden window', async () => {
  vi.useFakeTimers(); vi.setSystemTime(100000)
  const fetch = vi.fn().mockResolvedValue(atTravel(100000))
  const { result, rerender } = renderHook(({ active }) => useTeamPositions(fetch, 'https://box.test', active), { initialProps: { active: true } })
  await act(async () => {})
  fetch.mockRejectedValue(new Error('offline'))
  await act(async () => { await vi.advanceTimersByTimeAsync(5000) })
  fetch.mockResolvedValue(atTravel(115000, true))
  await act(async () => { await vi.advanceTimersByTimeAsync(10000) })
  expect(result.current.teleports).toHaveLength(0)
  rerender({ active: false })
  fetch.mockResolvedValue(atTravel(120000))
  rerender({ active: true })
  await act(async () => {})
  expect(result.current.teleports).toHaveLength(0)
})
