import { act, renderHook } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { getPlayerProgress, type PlayerProgressResponse } from '../api';
import { usePlayerProgress } from './usePlayerProgress';
vi.mock('../api', () => ({ getPlayerProgress: vi.fn() }));
afterEach(() => { vi.useRealTimers(); vi.resetAllMocks(); });
const response = (user_id: string): PlayerProgressResponse => ({ user_id, status: 'not_collected', baseline: null, checkpoints: [], changes: [], checkpoint_total: 0, change_total: 0 });
it('aborts a previous player and ignores its late response', async () => {
  let resolve!: (data: PlayerProgressResponse) => void;
  vi.mocked(getPlayerProgress).mockImplementationOnce(() => new Promise(r => { resolve = r; }));
  const { result, rerender } = renderHook(({ user }) => usePlayerProgress(true, user, 'history', 1000, 2000), { initialProps: { user: 'a' } });
  const signal = vi.mocked(getPlayerProgress).mock.calls[0][4];
  vi.mocked(getPlayerProgress).mockResolvedValueOnce(response('b'));
  rerender({ user: 'b' });
  expect(result.current.data).toBeUndefined();
  expect(signal?.aborted).toBe(true);
  await act(async () => {});
  await act(async () => resolve(response('a')));
  expect(result.current.data?.user_id).toBe('b');
});
it('isolates historical data from live data and caches historical windows', async () => {
  vi.mocked(getPlayerProgress).mockResolvedValue(response('a'));
  const { result, rerender } = renderHook(({ mode }) => usePlayerProgress(true, 'a', mode, 1000, 2000), { initialProps: { mode: 'live' as 'live' | 'history' } });
  await act(async () => {});
  rerender({ mode: 'history' });
  expect(result.current.data).toBeUndefined();
  await act(async () => {});
  expect(getPlayerProgress).toHaveBeenCalledTimes(2);
  rerender({ mode: 'live' });
  await act(async () => {});
  rerender({ mode: 'history' });
  await act(async () => {});
  expect(getPlayerProgress).toHaveBeenCalledTimes(3);
});
it('serializes slow live requests, waits 60 seconds after completion and stops when inactive', async () => {
  vi.useFakeTimers();
  let resolve!: (data: PlayerProgressResponse) => void;
  vi.mocked(getPlayerProgress).mockImplementationOnce(() => new Promise(r => { resolve = r; }));
  const { rerender } = renderHook(({ active }) => usePlayerProgress(active, 'a', 'live', 1000, 2000), { initialProps: { active: true } });
  await act(async () => { vi.advanceTimersByTime(15000); });
  expect(getPlayerProgress).toHaveBeenCalledTimes(1);
  vi.mocked(getPlayerProgress).mockResolvedValue(response('a'));
  await act(async () => resolve(response('a')));
  await act(async () => { vi.advanceTimersByTime(59999); });
  expect(getPlayerProgress).toHaveBeenCalledTimes(1);
  await act(async () => { vi.advanceTimersByTime(1); });
  expect(getPlayerProgress).toHaveBeenCalledTimes(2);
  rerender({ active: false });
  await act(async () => { vi.advanceTimersByTime(120000); });
  expect(getPlayerProgress).toHaveBeenCalledTimes(2);
});
it('refreshes a cached history on revision and never polls while history is idle', async () => {
  vi.useFakeTimers();
  vi.mocked(getPlayerProgress).mockResolvedValue(response('a'));
  const { rerender } = renderHook(({ revision }) => usePlayerProgress(true, 'a', 'history', 1000, 2000, revision), { initialProps: { revision: 0 } });
  await act(async () => {});
  await act(async () => { vi.advanceTimersByTime(120000); });
  expect(getPlayerProgress).toHaveBeenCalledTimes(1);
  rerender({ revision: 1 });
  await act(async () => {});
  expect(getPlayerProgress).toHaveBeenCalledTimes(2);
});
it('makes no request for an inactive workspace and aborts its in-flight request on hiding', async () => {
  vi.mocked(getPlayerProgress).mockImplementation(() => new Promise(() => {}));
  const { rerender } = renderHook(({ active }) => usePlayerProgress(active, 'a', 'live', 1000, 2000), { initialProps: { active: false } });
  expect(getPlayerProgress).not.toHaveBeenCalled();
  rerender({ active: true });
  const signal = vi.mocked(getPlayerProgress).mock.calls[0][4];
  rerender({ active: false });
  expect(signal?.aborted).toBe(true);
});
